#!/bin/bash
# vim:syntax=sh filetype=sh


## Define os-platorm
export PLATFORM_ARCH="$(uname -s)" # Linux | Darwin | ...

case $PLATFORM_ARCH in 
  Linux)
    if command -v dnf > /dev/null; then
      export PLATFORM_OS="Fedora";
    elif command -v apt > /dev/null; then
      export PLATFORM_OS="Ubuntu";
    else
      echo "Unsupported linux distro $(uname -a)"
    fi
    ;;
  Darwin)
    export PLATFORM_OS="MacOS"; return;
    ;;
  *)
    echo "Invalid option $PLATFORM_ARCH"
esac

echo "PLATFORM_ARCH=$PLATFORM_ARCH; OS=$PLATFORM_OS"

### Install base libs
if [ $PLATFORM_OS == "Fedora" ]; then
  sudo dnf upgrade -y 
  sudo dnf groupinstall @development-tools @development-libraries
  sudo dnf install @development-tools
  sudo dnf install -y \
    automake \
    curl \
    gcc \
    gcc-c++ \
    git \
    kernel-devel \
    libpq-devel \
    lua \
    make \
    neovim \
    nodejs \
    python3 \
    python3-devel \
    python3-pip \
    readline \
    readline-devel \
    tmux \
    wget \
    zsh 

  sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
  sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
  sudo dnf install 1password

elif [ $PLATFORM_OS == "Ubuntu" ]; then
  sudo apt upgrade -y
  sudo apt install -y build-essential \
    apt-transport-https \
    curl \
    git \
    gnupg2 \
    libpq-dev \
    libreadline-dev \
    lua5.3 \
    neovim \
    python3 \
    python3-dev \
    python3-pip \
    tmux \
    wget \
    zsh 

  echo "[INFO] 1Password playbook..."
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list
  sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
  curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
  sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  sudo apt update && sudo apt install 1password

  if command -v op > /dev/null; then
    echo "[INFO] 1Password installed with success"
  else
    echo "[ERROR] The 1Password hasn't installed!"
  fi

elif [ $PLATFORM_OS == "MacOS" ]; then
  brew upgrade -y

else
  echo "Unsupported platorm"

fi

